name 'mgarrison-dotnet'
version '0.0.1'

author 'mgarrison'
license 'CopyRight PartsSource Inc. 2012'
project_page 'UNKNOWN'
source 'UNKNOWN'
summary 'Installs .Net Framework'
description 'Installs and manages .Net Framework version 4'
